// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Synchronization.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var inexor = __M.module("inexor");

    inexor.tree = __M.module("inexor.tree");

    inexor.tree.Synchronization = Slice.defineObject(
        undefined,
        Ice.Object, undefined, 1,
        [
            "::Ice::Object",
            "::inexor::tree::Synchronization"
        ],
        -1, undefined, undefined, false);

    inexor.tree.SynchronizationPrx = Slice.defineProxy(Ice.ObjectPrx, inexor.tree.Synchronization.ice_staticId, undefined);

    Slice.defineOperations(inexor.tree.Synchronization, inexor.tree.SynchronizationPrx,
    {
        "printString": [, , , , , , [[7]], , , , ]
    });
    exports.inexor = inexor;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : window.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : window));
